<!-- Slider main container -->
<div class="swiper-container carousel">
	<!-- Additional required wrapper -->
	<div class="swiper-wrapper">
			<!-- Slides -->
			<div class="swiper-slide">
				<a href="/digital-product-humblebee">

				<div class="card one" id="one">
<!--
					<div class="card-text--white">
						<h4>HUMBLEBEE</h4>
						<h2>Digital<br />Product</h2>
					</div>
					<div class="card-img">
						<img class="card-img--morningmonster" src="<?php// echo get_bloginfo( 'template_directory' ); ?>/images/project-image--morningmonster.png" />
					</div> -->
				</div>
			</a>

			</div>

			<div class="swiper-slide">
				<a href="/digital-product-humblebee">

				<div class="card one" id="one">
<!--
					<div class="card-text--white">
						<h4>HUMBLEBEE</h4>
						<h2>Digital<br />Product</h2>
					</div>
					<div class="card-img">
						<img class="card-img--morningmonster" src="<?php// echo get_bloginfo( 'template_directory' ); ?>/images/project-image--morningmonster.png" />
					</div> -->
				</div>
			</a>

			</div>

			<div class="swiper-slide">
				<a href="/digital-product-humblebee">

				<div class="card one" id="one">
<!--
					<div class="card-text--white">
						<h4>HUMBLEBEE</h4>
						<h2>Digital<br />Product</h2>
					</div>
					<div class="card-img">
						<img class="card-img--morningmonster" src="<?php// echo get_bloginfo( 'template_directory' ); ?>/images/project-image--morningmonster.png" />
					</div> -->
				</div>
			</a>

			</div>

			<div class="swiper-slide">
				<a href="/digital-product-humblebee">

				<div class="card one" id="one">
<!--
					<div class="card-text--white">
						<h4>HUMBLEBEE</h4>
						<h2>Digital<br />Product</h2>
					</div>
					<div class="card-img">
						<img class="card-img--morningmonster" src="<?php// echo get_bloginfo( 'template_directory' ); ?>/images/project-image--morningmonster.png" />
					</div> -->
				</div>
			</a>

			</div>

			<div class="swiper-slide">
				<a href="/digital-product-humblebee">

				<div class="card one" id="one">
<!--
					<div class="card-text--white">
						<h4>HUMBLEBEE</h4>
						<h2>Digital<br />Product</h2>
					</div>
					<div class="card-img">
						<img class="card-img--morningmonster" src="<?php// echo get_bloginfo( 'template_directory' ); ?>/images/project-image--morningmonster.png" />
					</div> -->
				</div>
			</a>

			</div>

			<div class="swiper-slide">
				<a href="/digital-product-humblebee">

				<div class="card one" id="one">
<!--
					<div class="card-text--white">
						<h4>HUMBLEBEE</h4>
						<h2>Digital<br />Product</h2>
					</div>
					<div class="card-img">
						<img class="card-img--morningmonster" src="<?php// echo get_bloginfo( 'template_directory' ); ?>/images/project-image--morningmonster.png" />
					</div> -->
				</div>
			</a>

			</div>

	</div>

</div>
