<div class="navbar--displaymode hide">

	<div class="navbar--displaymode__icons">

		<div class="carousel-mode__btn selected" tooltip-content="Carousel layout" tooltip-position="left">
				<div class="icn-carousel--frame">
					<div class="icn-carousel--card default"></div>
					<div class="icn-carousel--card default"></div>
					<div class="icn-carousel--card default">  </div>
					<div class="icn-carousel--card default"></div>
				</div>
		</div>

		<div class="grid-mode__btn" tooltip-content="Overview layout" tooltip-position="right">
				<div class="icn-grid--frame">
						<div class="icn-grid--card"></div>
						<div class="icn-grid--card"></div>
						<div class="icn-grid--card"></div>
						<div class="icn-grid--card"></div>
						<div class="icn-grid--card"></div>
						<div class="icn-grid--card"></div>
				</div>
		</div>

	</div>

	<span class="paragraph-xs center display-mode__caption">Change grid (G)</span>

</div>
