<div class="module-card-33 hide-grid ui--black">

	<div class="row-33">
				<a href="/digital-product-humblebee">
						<div class="card-33 one ">
									<div class="card-33--left">
										<h6 class="color-white">HUMBLEBEE</h6>
										<h3 class="color-white">Digital<br />Product</h3>
									</div>
									<div class="card-33--right">
										<img class="card-33--image" src="<?php echo get_bloginfo( 'template_directory' ); ?>/images/project-image--morningmonster.png" />
									</div>
						</div>
				</a>

				<a href="/branding-project-agrowth">
						<div class="card-33 two ">
									<div class="card-33--left">
										<h6 class="color-black">AGROWTH</h6>
										<h3 class="color-black">Branding<br />Project</h3>
									</div>
									<div class="card-33--right">
										<img class="card-33--image" src="<?php echo get_bloginfo( 'template_directory' ); ?>/images/project-image--agrowth.png" />
									</div>
						</div>
				</a>

				<a href="/travel-app-yrgo">
						<div class="card-33 three ">
									<div class="card-33--left">
										<h6 class="color-white">YRGO</h6>
										<h3 class="color-white">Travel<br />App</h3>
									</div>
									<div class="card-33--right">
										<img class="card-33--image" src="<?php echo get_bloginfo( 'template_directory' ); ?>/images/project-image--caribou.png" />
									</div>
						</div>
				</a>

	</div>
	<div class="row-33">
				<a href="/product-branding-int3-software">
						<div class="card-33 four ">
									<div class="card-33--left">
										<h6 class="color-white">INT3 SOFTWARE</h6>
										<h3 class="color-white">Product<br />Branding</h3>
									</div>
									<div class="card-33--right">
										<img class="card-33--image" src="<?php echo get_bloginfo( 'template_directory' ); ?>/images/project-image--int3.png" />
									</div>
						</div>
				</a>

				<a href="/photo-composition-personal">
						<div class="card-33 five ">
									<div class="card-33--left">
										<h6 class="color-black">PERSONAL</h6>
										<h3 class="color-black">Photo<br />Composition</h3>
									</div>
									<div class="card-33--right">
										<img class="card-33--image" src="<?php echo get_bloginfo( 'template_directory' ); ?>/images/project-image--castleofsand.jpg" />
									</div>
						</div>
				</a>

				<a href="/freebies">
						<div class="card-33 six ">
									<div class="card-33--left">
										<h6 class="color-white">DOWNLOAD</h6>
										<h3 class="color-white">Freebies<br />a la Max</h3>
									</div>
									<div class="card-33--right">
										<img class="card-33--image" src="<?php echo get_bloginfo( 'template_directory' ); ?>/images/project-image--freebies.png" />
									</div>
						</div>
				</a>

	</div>
</div>
