<div class="grid-mode hide">
	<div class="grid-mode--container">
		<?php

		$currentID = get_the_ID();
		$args = array(
		'post_type' => 'projects',
		'posts_per_page' => -1,
		'orderby' => 'post_date',
		'order' => 'DESC'
		);


		// The Query
		$query = new WP_Query( $args );
		$a = -1;
		$i = 0;

		// The Loop
		if ( $query->have_posts() ) : while ( $query->have_posts() ) :
			$query->the_post();?>

			<?php if( have_rows('project_card') ):

						while( have_rows('project_card') ): the_row();

							// vars
							$client = get_sub_field('client');
							$name = get_sub_field('name');
							$alt = get_sub_field('alt_text');
							$image = get_sub_field('image');
							$i++;
							$a++;
							$gradient = array("image-archive-discoverability", "checkout-page-optimisation", "make-product-preview-better", "typeface-design", "website-redesign", "illustrations");
							?>

							<a class="card-link" href="<?php the_permalink(); ?>">

								<div class="card grid animation--gridreveal <?= $gradient[$a]; ?>--gradient project-<?= $i ?>">
									
									<div class="left-container">
										<h5 class="sub-heading-four light"><?= $client ?></h5>
										<h2 class="heading-four light"><?= $name ?></h2>
									</div>

									<div class="right-container">
										<?php	if( !empty($image) ):

											echo add_image(
												$image,  // ACF-field
												'g_south,q_70,c_fill,f_auto', // Parameters
												'featured-image', // Classes
												$alt // alt text
											);

										endif; ?>

									</div>
								</div>
							</a>	

					<?php endwhile; ?>

			<?php endif; ?>


		<?php endwhile; endif;?>
	</div>
</div>
