<?php if( have_rows('modal_menu', 'option') ):?>

    <?php	while( have_rows('modal_menu', 'option') ): the_row();

    // vars
    $heading = get_sub_field('heading', 'option');
    $paragraph = get_sub_field('paragraph', 'option');

    ?>

<div class="modal modal--menu">

  <div class="modal--container">

    <div class="modal__close">
      	<?php add_icon('icn-close'); ?>
    </div>


      <div class="modal--content">

        <h3 class="heading-two"><?= $heading ?></h3>
        <p class="paragraph-sm"><?= $paragraph ?></p>

        <?php if( have_rows('menu_links') ):?>

          <ul class="menu--container">

            <?php	while( have_rows('menu_links') ): the_row();

            // vars
            $link = get_sub_field('menu_link', 'option');
            $url = $link['url'];
            $label = $link['title'];
            $link_target = $link['target'] ? $link['target'] : '_self';

            ?>
            <li class="menu--link">
              <a href="<?= $url ?>" target="<?= $link_target ?>" onclick="location.reload()" class="heading-four link"> <?= $label ?> </a>
            </li>

          <?php endwhile; ?>

        </ul>

      <?php endif; ?>

      </div>

    </div>

    <div class="overlay-blur"></div>

</div>

<?php endwhile; ?>

<?php endif; ?>
