<div class="notification-placement">

  <div class="notification start-message">

    <div class="notification--content">
      <p class="paragraph-sm no-margin">
        Use your keyboard to navigate the site<br /><a class="link" href="#website-shortcuts">See shortcuts (S)</a>
      </p>
    </div>

    <div class="notification--btn">
      <?php add_icon('icn-close'); ?>
    </div>

  </div>

</div>
