<?php
  $bgimg = get_field('preloader_bg','option');

?>


<div class="grid preloader">

  <div class="row">

    <div class="preloader--container hide">

      <p class="preloader--text paragraph center">"Even miracles take a little time"</p>
      <div class="bar"><div class="progress"></div></div>
      <p class="paragraph-xs center"><span class="counter">0</span> %</p>

    </div>

  </div>
</div>
