<div class="project-overview ui-section light-section">
	<h4 class="heading-three light center">Other projects</h4>
		<div class="project-overview--container">
				<?php

				$current = get_the_ID();

				$args = array(
				'post_type' => 'projects',
				'posts_per_page' => -1,
				'orderby' => 'post_date',
				'order' => 'DESC',
				//'post__not_in' => array($current)
				);


				// The Query
				$query = new WP_Query( $args );
				$a = -1;
				$i = 0;

				// The Loop
				if ( $query->have_posts() ) : while ( $query->have_posts() ) :
					$query->the_post();?>

					<?php if( have_rows('project_card') ):

								while( have_rows('project_card') ): the_row();

									// vars
									$client = get_sub_field('client');
									$name = get_sub_field('name');
									$alt_text = get_sub_field('alt_text');
									$image = get_sub_field('image');
									$i++;
									$a++;
									$gradient = array("agrowth", "sendify", "thunberg-sans", "express-delivery", "humblebee", "int3-software");
									?>
								<div class="card-container">


										<a class="card-link" href="<?php the_permalink(); ?>">

											<div class="card-sm <?= $gradient[$a]; ?>--gradient project-<?= $i ?>">

														<div class="cardclick cardclick-<?= $i ?>"></div>

														<div class="card-left">
															<div class="card-text">
																<h5 class="sub-heading-four light"><?= $client ?></h5>
																<h2 class="heading-four light"><?= $name ?></h2>
															</div>
														</div>

														<div class="card-right">
															<?php	if( !empty($image) ):

																				echo add_image(
																					$image,  // ACF-field
																					'g_south,q_70,h_200,c_fill', // Parameters
																					'featured-image', // Classes
																					$alttext // alt text
																				);

																			endif; ?>

														</div>

											</div>
										</a>
									</div>

							<?php endwhile; ?>

					<?php endif; ?>


				<?php endwhile; endif;?>
	</div>
</div>
